import { useEffect, useRef, useState } from "react";
import mermaid from "mermaid";
import { useRoadmapStore } from "@/stores/useRoadmapStore";
import type { RoadmapData } from "@/stores/useRoadmapStore";

interface MermaidProps {
  roadmap: RoadmapData;
}

export default function MermaidMindmap({ roadmap }: MermaidProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svgContent, setSvgContent] = useState<string>("");
  const { setSelectedNode, trackMode } = useRoadmapStore();

  useEffect(() => {
    mermaid.initialize({
      startOnLoad: false,
      theme: "base",
      themeVariables: {
        fontFamily: "Inter, sans-serif",
      },
      securityLevel: 'loose' // allow click events
    });

    const generateMermaidSyntax = () => {
      let syntax = "graph LR\n";
      
      // Start Node
      syntax += `  START([${roadmap.current_state.label}<br/>Score: ${roadmap.current_state.score}]):::start\n\n`;

      // Draw tracks
      roadmap.tracks.forEach(track => {
        syntax += `  subgraph ${track.track_id}["${track.track_name}"]\n`;
        
        let previousNodeId = "START";
        
        track.nodes.forEach(node => {
          // Filter by track mode if needed
          if (trackMode === 'fast' && (node.priority === 'medium' || node.priority === 'low')) {
            return;
          }

          let shapeStart = "[";
          let shapeEnd = "]";
          if (node.type === "certification") {
            shapeStart = "((";
            shapeEnd = "))";
          } else if (node.type === "skill") {
            shapeStart = "([";
            shapeEnd = "])";
          }
          
          syntax += `    ${node.id}${shapeStart}"${node.label}<br/><i>${node.duration}</i>"${shapeEnd}:::${node.priority}\n`;
          
          if (node.depends_on && node.depends_on.length > 0) {
            node.depends_on.forEach(dep => {
              syntax += `    ${dep} --> ${node.id}\n`;
            });
          } else {
            syntax += `    ${previousNodeId} --> ${node.id}\n`;
          }
          previousNodeId = node.id;
          
          // Add click event for interaction
          syntax += `    click ${node.id} clickHandler "${node.label}"\n`;
        });
        
        syntax += `  end\n\n`;
      });

      // Milestones
      roadmap.milestones.forEach(m => {
        syntax += `  ${m.id}{"${m.label}<br/>Week ${m.at_week}"}:::milestone\n`;
        m.requires.forEach(req => {
          syntax += `  ${req} --> ${m.id}\n`;
        });
      });

      // Class definitions
      syntax += `\n`;
      syntax += `  classDef critical fill:#ef4444,stroke:#991b1b,color:#fff,stroke-width:2px\n`;
      syntax += `  classDef high fill:#f97316,stroke:#c2410c,color:#fff,stroke-width:2px\n`;
      syntax += `  classDef medium fill:#facc15,stroke:#ca8a04,color:#000,stroke-width:2px\n`;
      syntax += `  classDef low fill:#4ade80,stroke:#16a34a,color:#000,stroke-width:2px\n`;
      syntax += `  classDef milestone fill:#fff,stroke:#3b82f6,stroke-width:3px,color:#1e3a8a,stroke-dasharray: 5 5\n`;
      syntax += `  classDef start fill:#1f2937,stroke:#000,color:#fff,stroke-width:2px\n`;

      return syntax;
    };

    const renderGraph = async () => {
      const syntax = generateMermaidSyntax();
      try {
        const { svg } = await mermaid.render("roadmap-graph", syntax);
        setSvgContent(svg);
      } catch (err) {
        console.error("Mermaid parsing failed", err);
      }
    };

    renderGraph();
  }, [roadmap, trackMode]);

  // Handle clicks generated by mermaid
  useEffect(() => {
    // Expose global function for Mermaid click binding
    (window as Window & typeof globalThis & { clickHandler?: (nodeId: string) => void }).clickHandler = (nodeId: string) => {
      // Find the node in data
      for (const track of roadmap.tracks) {
        const node = track.nodes.find(n => n.id === nodeId);
        if (node) {
          setSelectedNode(node);
          return;
        }
      }
    };

    return () => {
      delete (window as Window & typeof globalThis & { clickHandler?: (nodeId: string) => void }).clickHandler;
    };
  }, [roadmap, setSelectedNode]);

  return (
    <div className="w-full h-full overflow-auto bg-gray-50 relative p-8 cursor-grab active:cursor-grabbing flex items-center justify-center">
      {/* Container for SVG */}
      <div 
        ref={containerRef} 
        className="mermaid-wrapper min-w-[800px]"
        dangerouslySetInnerHTML={{ __html: svgContent }}
      />
    </div>
  );
}
